### ISSUE TITLE
Update logo and nav menu

### ISSUE THREAD

**Issue by jonaswagner2826** [Applied-Systems-Lab/Applied-Systems-Lab.github.io#2]

**Comment by jruths** [comment]
@jonaswagner2826   Ok, I put the current logo idea into the assets/img folder.  For now, let's try using the horizontal one.  Since that image includes the "applied systems" text, I think we can leave off the title text that is currently on the page?  

I was also wondering if we could put the Nova icon as an element of the upper nav menu instead of in the header at the top? Essentially just to the right of "research" in the nav menu.

**Comment by jonaswagner2826** [comment]
@jruths It should be updated now. Do you want NOVA to have a page as well or just direct straight to the website?

EDIT: (nm... it actually didn't deploy as I thought it would... debugging now)

**Comment by jruths** [comment]
It can go straight to Nova.  Thanks!

**Comment by jonaswagner2826** [comment]
okay... it should be fixed now.
For the "leave off the title text that is currently on the page" do you mean the one that's on the main/about page or just in the header on the other pages?
